---
title: "Waves"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wavelogger

This is for managing and understanding your open wave height logger data

## Requirements

  + [R v4+](https://www.r-project.org/)
  + [dplyr](https://CRAN.R-project.org/package=dplyr)
  + [readr](https://CRAN.R-project.org/package=readr)
  + [stringr](https://CRAN.R-project.org/package=stringr)
  + [ggplot2](https://CRAN.R-project.org/package=ggplot2)
  + [oceanwaves](https://CRAN.R-project.org/package=oceanwaves)
  + [oce](https://CRAN.R-project.org/package=oce)
  + [owhlR](https://github.com/millerlp/owhlR) *from github*
  + [mesowest](https://github.com/fickse/mesowest) *from github*

## Installation

```
remotes::install_github("rfrancolini/wavelogger")
```


## Read Example Data

```{r exampleData}
library(wavelogger)
x <- read_wavelogger()
head(x)
```

## Read Air Pressure Data Example

```{r Airpressure}
a <- example_airpressure()
head(a)
```

## Calculate Wave Statistcs

```{r WaveStats}
i <- interp_swpressure(wavelogger = x, airpressure = a)

w <- wave_stats(wavelogger = mbar_to_elevation(wavelogger = i)) 

head(w)
```

## Graph Significant Wave Height
```{r GraphWaves}
wave_plot <- wavespec_plot(w)
wave_plot
```

